---

- name: KAFKA | Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - kafka_install

- name: KAFKA | Agent config
  ansible.builtin.import_tasks: agent.yml
  tags:
    - kafka_agents_config
  when: kafka_agents_config is defined

- name: KAFKA | Install plugins
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: "{{ ['kafka_plugins_tasks'] + (kafka_plugins_tasks_tags | default([])) }}"
  loop: "{{ kafka_plugins_tasks }}"
  tags: "{{ ['kafka_plugins_tasks'] + (kafka_plugins_tasks_tags | default([])) }}"
  when: kafka_plugins_tasks is defined

- name: KAFKA | Configure
  ansible.builtin.import_tasks: config.yml
  tags:
    - kafka_configure

- name: KAFKA | Service
  ansible.builtin.import_tasks: service.yml
  tags:
    - kafka_service

- name: KAFKA | Topics (2.X Version)
  ansible.builtin.import_tasks: 2.0/topics.yml
  run_once: true
  when: kafka_version is version('3.0.0', "<")
  tags:
    - kafka_topics

- name: KAFKA | Topics (>= 3.X Version)
  ansible.builtin.import_tasks: 3.0/topics.yml
  run_once: true
  when: kafka_version is version('3.0.0', ">=")
  tags:
    - kafka_topics

- name: KAFKA | ACLs
  ansible.builtin.import_tasks: acls.yml
  tags:
    - kafka_acls
  when: kafka_acls is defined
  run_once: true

- name: KAFKA | Extra tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: "{{ ['kafka_extra_tasks'] + (kafka_extra_tasks_tags | default([])) }}"
  loop: "{{ kafka_extra_tasks }}"
  tags: "{{ ['kafka_extra_tasks'] + (kafka_extra_tasks_tags | default([])) }}"
  when: kafka_extra_tasks is defined
