# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

STOPSIGNAL SIGRTMIN+3
RUN systemctl set-default multi-user.target
# TIP 2 solution 2
# RUN systemctl mask getty.target

RUN mkdir -p /usr/share/man/man1