---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: kafka1
    hostname: kafka1
    image: ${MOLECULE_DISTRO:-idealista/jdk:17.0.8-bullseye-temurin-jdk}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    exposed_ports:
      - 9091/tcp
      - 9092/tcp
      - 9093/tcp
    published_ports:
      - 0.0.0.0:19091:9091/tcp
      - 0.0.0.0:19092:9092/tcp
      - 0.0.0.0:19093:9093/tcp
    cgroupns_mode: host

  - name: kafka2
    hostname: kafka2
    image: ${MOLECULE_DISTRO:-idealista/jdk:17.0.8-bullseye-temurin-jdk}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    exposed_ports:
      - 9091/tcp
      - 9092/tcp
      - 9093/tcp
    published_ports:
      - 0.0.0.0:29091:9091/tcp
      - 0.0.0.0:29092:9092/tcp
      - 0.0.0.0:29093:9093/tcp
    cgroupns_mode: host

  - name: kafka3
    hostname: kafka3
    image: ${MOLECULE_DISTRO:-idealista/jdk:17.0.8-bullseye-temurin-jdk}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    exposed_ports:
      - 9091/tcp
      - 9092/tcp
      - 9093/tcp
    published_ports:
      - 0.0.0.0:39091:9091/tcp
      - 0.0.0.0:39092:9092/tcp
      - 0.0.0.0:39093:9093/tcp
    cgroupns_mode: host

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  lint:
    - name: ansible-lint
    - name: yamllint
  config_options:
    defaults:
      callback_result_format: yaml
      callbacks_enabled: timer, profile_tasks, profile_roles
      show_per_host_start: true
      show_custom_stats: true
      fact_caching: yaml
      # fact_caching_connection: ./tmp/facts_cache

scenario:
  name: default

verifier:
  name: ansible
