---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    exposed_ports:
      - 2181/tcp
    published_ports:
      - 2181:2181
    command: "sh /etc/confluent/docker/run"
    env:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    groups:
      - zookeeper
    networks:
      - name: kafka-network
    cgroupns_mode: host

  - name: kafka1
    hostname: kafka1
    image: ${MOLECULE_DISTRO:-idealista/jdk:8u302-bullseye-corretto-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9092:9092/tcp
    cgroupns_mode: host

  - name: kafka2
    hostname: kafka2
    image: ${MOLECULE_DISTRO:-idealista/jdk:8u302-bullseye-corretto-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9093:9092/tcp
    cgroupns_mode: host

  - name: kafka3
    hostname: kafka3
    image: ${MOLECULE_DISTRO:-idealista/jdk:8u302-bullseye-corretto-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9094:9092/tcp
    cgroupns_mode: host

provisioner:
  name: ansible
  lint:
    - name: ansible-lint
    - name: yamllint

scenario:
  name: default

verifier:
  name: ansible
